Watching for file changes with StatReloader
Internal Server Error: /hotprojects
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 25, in hotprojects
    return JsonResponse(result)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/http/response.py", line 560, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
"GET /hotprojects HTTP/1.1" 500 76053
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3090
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hotprojects HTTP/1.1" 200 1439
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hotprojects HTTP/1.1" 200 1057
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hotprojects HTTP/1.1" 200 1055
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hotprojects HTTP/1.1" 200 1055
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hotprojects HTTP/1.1" 200 9
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /hotprojects
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 27, in hotprojects
    return JsonResponse(json.dumps(result))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/http/response.py", line 560, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
"GET /hotprojects HTTP/1.1" 500 73617
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hotprojects HTTP/1.1" 200 1470
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hotprojects HTTP/1.1" 200 9
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /hotprojects
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 28, in hotprojects
    return JsonResponse(insa_project_list.data)
AttributeError: 'str' object has no attribute 'data'
"GET /hotprojects HTTP/1.1" 500 66214
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /hotprojects
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 202, in _get_response
    response = response.render()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/rest_framework/response.py", line 55, in rendered_content
    assert renderer, ".accepted_renderer not set on Response"
AssertionError: .accepted_renderer not set on Response
"GET /hotprojects HTTP/1.1" 500 65683
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /hotprojects
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 202, in _get_response
    response = response.render()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/rest_framework/renderers.py", line 723, in render
    template = loader.get_template(self.template)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html
"GET /hotprojects HTTP/1.1" 500 79253
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /hotprojects
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 202, in _get_response
    response = response.render()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/rest_framework/renderers.py", line 723, in render
    template = loader.get_template(self.template)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: rest_framework/api.html
"GET /hotprojects HTTP/1.1" 500 79253
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hotprojects HTTP/1.1" 200 1057
"GET /hotprojects HTTP/1.1" 200 1057
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hotprojects HTTP/1.1" 200 1057
Watching for file changes with StatReloader
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/learningfair/settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /hotprojects HTTP/1.1" 200 933
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /hotprojects
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 28, in hotprojects
    return JsonResponse(success(statusCode.OK, resMessage.OK, data))
AttributeError: 'dict' object has no attribute 'OK'
"GET /hotprojects HTTP/1.1" 500 63622
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /hotprojects
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 28, in hotprojects
    return JsonResponse(success(statusCode['OK'], resMessage['OK'], data))
KeyError: 'OK'
"GET /hotprojects HTTP/1.1" 500 63462
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /hotprojects
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 28, in hotprojects
    return JsonResponse(success(statusCode['SUCCESS'], resMessage['OK'], data))
KeyError: 'SUCCESS'
"GET /hotprojects HTTP/1.1" 500 63492
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hotprojects HTTP/1.1" 200 1010
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hotprojects HTTP/1.1" 200 1020
Watching for file changes with StatReloader
"GET /hotprojects HTTP/1.1" 200 1020
Forbidden (CSRF cookie not set.): /hotprojects
"POST /hotprojects HTTP/1.1" 403 2994
Forbidden (CSRF cookie not set.): /hotprojects
"DELETE /hotprojects HTTP/1.1" 403 2994
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /hotprojects
"DELETE /hotprojects HTTP/1.1" 400 111
Bad Request: /hotprojects
"POST /hotprojects HTTP/1.1" 400 111
"GET /hotprojects HTTP/1.1" 200 1020
Watching for file changes with StatReloader
Bad Request: /hotprojects
"POST /hotprojects HTTP/1.1" 400 111
"GET /hotprojects HTTP/1.1" 200 1020
Watching for file changes with StatReloader
"GET /hotprojects HTTP/1.1" 200 2571
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 2491
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 7462
"GET /admin/applications/notice/add/ HTTP/1.1" 200 8996
"GET /admin/jsi18n/ HTTP/1.1" 200 8314
"POST /admin/applications/notice/add/ HTTP/1.1" 302 0
"GET /admin/applications/notice/ HTTP/1.1" 200 8436
"GET /admin/jsi18n/ HTTP/1.1" 200 8314
"GET /admin/applications/notice/add/ HTTP/1.1" 200 8996
"GET /admin/jsi18n/ HTTP/1.1" 200 8314
"POST /admin/applications/notice/add/ HTTP/1.1" 302 0
"GET /admin/applications/notice/ HTTP/1.1" 200 8754
"GET /admin/jsi18n/ HTTP/1.1" 200 8314
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/modules.py changed, reloading.
Watching for file changes with StatReloader
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/modules.py changed, reloading.
Watching for file changes with StatReloader
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /lectures/02/projects HTTP/1.1" 200 1052
"GET /projects?searchBy=%27%EB%A9%94%EB%A1%B1%27 HTTP/1.1" 200 79
"GET /projects?searchBy=%EB%A9%94%EB%A1%B1 HTTP/1.1" 200 79
"GET /projects?searchBy=merong HTTP/1.1" 200 410
"GET /notices HTTP/1.1" 200 282
Watching for file changes with StatReloader
Internal Server Error: /projects/02/likes
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 104, in project_likes
    project = Project.objects.get(id=id)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
applications.models.Project.DoesNotExist: Project matching query does not exist.
"POST /projects/02/likes HTTP/1.1" 500 72700
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /projects/02/likes
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 104, in project_likes
    project = Project.objects.get(id=id)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
applications.models.Project.DoesNotExist: Project matching query does not exist.
"POST /projects/02/likes HTTP/1.1" 500 72701
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/urls.py changed, reloading.
Watching for file changes with StatReloader
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lectures/02/groups/02/like
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 105, in project_likes
    project = Project.objects.get(lecture=lecture_id, group_id=group_id)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1258, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1084, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1481, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'group_id' into field. Choices are: description, group, groupName, id, lecture, likeCount, members, pdf, title, video
"POST /lectures/02/groups/02/like HTTP/1.1" 500 114238
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lectures/02/groups/02/like
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 105, in project_likes
    project = Project.objects.get(lecture=lecture_id, group_id=group_id)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1258, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1084, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1481, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'group_id' into field. Choices are: description, group, groupName, id, lecture, likeCount, members, pdf, title, video
"POST /lectures/02/groups/02/like HTTP/1.1" 500 114431
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /lectures/02/projects/02/like
"GET /lectures/02/projects/02/like HTTP/1.1" 404 3164
Internal Server Error: /lectures/02/groups/02/like
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 105, in project_likes
    project = Project.objects.get(lecture=lecture_id, group_id=group_id)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1258, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1084, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1481, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'group_id' into field. Choices are: description, group, groupName, id, lecture, likeCount, members, pdf, title, video
"GET /lectures/02/groups/02/like HTTP/1.1" 500 116309
"GET /hotprojects HTTP/1.1" 200 2576
"GET /hotprojects HTTP/1.1" 200 2576
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lectures/02/groups/02/like
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 108, in project_likes
    return JsonResponse(success(statusCode['OK'], resMessage['LIKE_CANCEL_SUCCESS'], project), status=statusCode['OK'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/http/response.py", line 567, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/serializers/json.py", line 105, in default
    return super().default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Project is not JSON serializable
"GET /lectures/02/groups/02/like HTTP/1.1" 500 92767
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lectures/02/groups/02/like
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 108, in project_likes
    data = project.values()
AttributeError: 'Project' object has no attribute 'values'
"GET /lectures/02/groups/02/like HTTP/1.1" 500 65992
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lectures/02/groups/02/like
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 106, in project_likes
    return JsonResponse(success(statusCode['OK'], resMessage['LIKE_CANCEL_SUCCESS'], project), status=statusCode['OK'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/http/response.py", line 567, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/serializers/json.py", line 105, in default
    return super().default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Project is not JSON serializable
"GET /lectures/02/groups/02/like HTTP/1.1" 500 92710
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lectures/02/groups/02/like
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 106, in project_likes
    return JsonResponse(success(statusCode['OK'], resMessage['LIKE_SUCCESS'], project), status=statusCode['OK'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/http/response.py", line 567, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/serializers/json.py", line 105, in default
    return super().default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Project is not JSON serializable
"GET /lectures/02/groups/02/like HTTP/1.1" 500 92696
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lectures/02/groups/02/like
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 106, in project_likes
    return JsonResponse(success(statusCode['OK'], resMessage['LIKE_SUCCESS']), status=statusCode['OK'])
TypeError: success() missing 1 required positional argument: 'data'
"GET /lectures/02/groups/02/like HTTP/1.1" 500 65983
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lectures/02/groups/02/like
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 109, in project_likes
    return JsonResponse(success(statusCode['OK'], resMessage['LIKE_SUCCESS'], project), status=statusCode['OK'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/http/response.py", line 567, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/serializers/json.py", line 105, in default
    return super().default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Project is not JSON serializable
"GET /lectures/02/groups/02/like HTTP/1.1" 500 92782
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lectures/02/groups/02/like
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 109, in project_likes
    return JsonResponse(success(statusCode['OK'], resMessage['LIKE_SUCCESS'], json.loads(project)), status=statusCode['OK'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not Project
"GET /lectures/02/groups/02/like HTTP/1.1" 500 71009
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /lectures/02/groups/02/like HTTP/1.1" 200 119
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lectures/02/groups/02/like
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 106, in project_likes
    print(project.values())
AttributeError: 'Project' object has no attribute 'values'
"GET /lectures/02/groups/02/like HTTP/1.1" 500 65700
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /lectures/02/groups/02/like HTTP/1.1" 200 128
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /login
"POST /login HTTP/1.1" 404 3096
Not Found: /login
"POST /login HTTP/1.1" 404 3096
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/urls.py changed, reloading.
Watching for file changes with StatReloader
"POST /login HTTP/1.1" 200 20
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
"POST /login HTTP/1.1" 200 16
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /login
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 124, in login
    return JsonResponse(req.body)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/http/response.py", line 560, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
"POST /login HTTP/1.1" 500 68103
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /login
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 123, in login
    new_user = User(studentId=info.studentId, name=info.name, comment=info.comment, major=info.major)
AttributeError: 'dict' object has no attribute 'studentId'
"POST /login HTTP/1.1" 500 63385
Internal Server Error: /login
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 123, in login
    new_user = User(studentId=info.studentId, name=info.name, comment=info.comment, major=info.major)
AttributeError: 'dict' object has no attribute 'studentId'
"POST /login HTTP/1.1" 500 63397
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /login
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 123, in login
    new_user = User(studentId=info['studentId'], name=info.name, comment=info.comment, major=info.major)
AttributeError: 'dict' object has no attribute 'name'
"POST /login HTTP/1.1" 500 63403
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /login
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 125, in login
    return JsonResponse(req.body)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/http/response.py", line 560, in __init__
    raise TypeError(
TypeError: In order to allow non-dict objects to be serialized set the safe parameter to False.
"POST /login HTTP/1.1" 500 68998
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /login
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 125, in login
    return JsonResponse(success(statusCode['CREATED'], resMessage['SUCCESS'], new_user), status=statusCode['CREATED'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/http/response.py", line 567, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/serializers/json.py", line 105, in default
    return super().default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type User is not JSON serializable
"POST /login HTTP/1.1" 500 90329
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /login
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 126, in login
    return JsonResponse(success(statusCode['CREATED'], resMessage['SUCCESS'], serializers.serialize(new_user)), status=statusCode['CREATED'])
TypeError: serialize() missing 1 required positional argument: 'queryset'
"POST /login HTTP/1.1" 500 63801
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /login
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 126, in login
    return JsonResponse(success(statusCode['CREATED'], resMessage['SUCCESS'], serializers.serialize('json', new_user)), status=statusCode['CREATED'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/serializers/__init__.py", line 128, in serialize
    s.serialize(queryset, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/serializers/base.py", line 90, in serialize
    for count, obj in enumerate(queryset, start=1):
TypeError: 'User' object is not iterable
"POST /login HTTP/1.1" 500 73604
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /login
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 126, in login
    return JsonResponse(success(statusCode['CREATED'], resMessage['SUCCESS'], serializers.deserialize('json', new_user)), status=statusCode['CREATED'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/http/response.py", line 567, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/serializers/json.py", line 105, in default
    return super().default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type generator is not JSON serializable
"POST /login HTTP/1.1" 500 90643
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /login
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 126, in login
    return JsonResponse(success(statusCode['CREATED'], resMessage['SUCCESS'], json.dumps(new_user)), status=statusCode['CREATED'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type User is not JSON serializable
"POST /login HTTP/1.1" 500 82060
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
"POST /login HTTP/1.1" 201 81
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
"DELETE /lectures/02/groups/02/like HTTP/1.1" 200 105
Bad Request: /lectures/02/groups/02/like
"POST /lectures/02/groups/02/like HTTP/1.1" 400 111
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
"POST /lectures/02/groups/02/like HTTP/1.1" 200 105
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
"DELETE /lectures/02/groups/02/like HTTP/1.1" 200 105
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
"DELETE /lectures/02/groups/02/like HTTP/1.1" 200 422
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /lectures/02/groups/02/like
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 106, in project_likes
    data = dict(project)
TypeError: 'Project' object is not iterable
"DELETE /lectures/02/groups/02/like HTTP/1.1" 500 63706
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
"POST /login HTTP/1.1" 201 359
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /login
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 119, in login
    return JsonResponse(success(statusCode['CREATED'], resMessage['SUCCESS'], [new_user]), status=statusCode['CREATED'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/http/response.py", line 567, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/serializers/json.py", line 105, in default
    return super().default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type User is not JSON serializable
"POST /login HTTP/1.1" 500 90394
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /login
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 120, in login
    return JsonResponse(success(statusCode['CREATED'], resMessage['SUCCESS'], json.dumps(model_to_dict(new_user))), status=statusCode['CREATED'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
"POST /login HTTP/1.1" 500 83342
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /login
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py", line 121, in login
    return JsonResponse(success(statusCode['CREATED'], resMessage['SUCCESS'], json.dumps(model_to_dict(new_user))), status=statusCode['CREATED'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
"POST /login HTTP/1.1" 500 83376
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
"POST /login HTTP/1.1" 201 286
/Users/brian/Documents/coding/LearningFair_Archiving_PJT_BE/learningfair/applications/views.py changed, reloading.
Watching for file changes with StatReloader
"POST /lectures/02/groups/02/like HTTP/1.1" 200 422
"POST /lectures/02/groups/02/like HTTP/1.1" 200 422
"DELETE /lectures/02/groups/02/like HTTP/1.1" 200 422
"DELETE /lectures/02/groups/02/like HTTP/1.1" 200 422
"GET /hotprojects HTTP/1.1" 200 2576
"GET /lectures/02/projects HTTP/1.1" 200 1052
"GET /projects?searchBy=merong HTTP/1.1" 200 410
"GET /notices HTTP/1.1" 200 282
"POST /login HTTP/1.1" 201 286
